swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /user:
    get:
      operationId: read_all
      x-swagger-router-controller: app.controllers.user_controller
      tags:
        - User
      parameters:
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
    post:
      operationId: insert
      x-swagger-router-controller: app.controllers.user_controller
      consumes:
      - multipart/form-data
      produces:
      - application/json
      tags:
        - User
      parameters:
        - name: user
          in: body
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
  # /file_uploader:
  #   post:
  #     operationId: create
  #     x-swagger-router-controller: app.controllers.file_uploader_controller
  #     tags:
  #       - Upload
  #     consumes:
  #       - multipart/form-data
  #     parameters:
  #       - name: file
  #         in: formData
  #         type: file
  #         required: true
  #       - name: output_file_name
  #         in: formData
  #         type: string
  #         required: true
  #       - name: count
  #         in: formData
  #         type: integer
  #         required: true
  #     responses:
  #       201:
  #         description: Success
  # /multi_file_uploader:
  #   post:
  #     operationId: create_multi_file
  #     x-swagger-router-controller: app.controllers.file_uploader_controller
  #     tags:
  #       - Upload
  #     consumes:
  #       - multipart/form-data
  #     parameters:
  #       - name: files
  #         properties:
  #           items:
  #           - name: file_name
  #             in: formData
  #             type: string
  #             required: true
  #           - name: file
  #             in: formData
  #             type: file
  #             required: true
  #     responses:
  #       201:
  #         description: Success
